name: Bug Report
description: Report a problem with wideriver
labels: [bug]
body:
  - type: textarea
    attributes:
      label: "Description"
      description: "A short description of the problem you are reporting. You can attach screenshots or videos. [grim](https://git.sr.ht/~emersion/grim/) and [wf-recorder](https://github.com/ammen99/wf-recorder) may be useful."
    validations:
      required: true
  - type: input
    attributes:
      label: "river version"
      description: "Output of `river -version`"
    validations:
      required: true
  - type: input
    attributes:
      label: "wideriver version"
      description: "Output of `wideriver --version`"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Logs"
      description: "Logs showing at minimum the startup arguments. Likely at `/tmp/wideriver.${XDG_VTNR}.${USER}.log`"
      render: text
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Steps to reproduce"
      description: "Steps to reproduce using the configuration shown in the logs"
    validations:
      required: true

